version: 0.2
phases:
  pre_build:
    commands:
      - cd ui
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - echo $secretfile > ./src/aws-exports.js
      - echo $environment > ./.env.production
      - npm run build:production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: ui/build
